slogan: "Dare to Learn! Learn to Dare!: 기록은 기억을 지배한다!~"

theme: sandstone
inverse: false

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: Dev-Roadmap
    url: Dev-Roadmap
    intro: "Dev-Roadmap."
    icon: "fa fa-code-fork"
  - title: ENG-Study-Ref
    url: ENG-Study-Ref
    intro: "ENG-Study-Ref."
    icon: "fa fa-globe"
  - title: Re-Invent-JS
    url: re-invent-js
    intro: "Re-Invent-JS."
    icon: "fa fa-refresh"
  - title: GraphQL
    url: GraphQL
    intro: "GraphQL."
    icon: "fa fa-pie-chart"
  - title: PRJTs
    url: PRJTs
    intro: "PRJTs by me."
    icon: "fa fa-tasks"
  - title: ABOUT-ME
    url: aboutME
    intro: "ABOUT-ME."
    icon: "fa fa-user"

links:
  - title: "HEXOBLG-DOCs"
    url: https://hexo.io/ko/docs/asset-folders.html
    intro: "HEXO-DOCs."
    icon: "fa fa-book"
  - title: "GIT-DOCs"
    url: https://git-scm.com/docs
    intro: "GIT-DOCs."
    icon: "fa fa-book"
  - title: "MD-GitHub"
    url: http://prose.io/#chan48
    intro: "MD-GitHub."
    icon: "fa fa-pencil-square"
  - title: "MD-DraftBX"
    url: https://stackedit.io/editor
    intro: "MD-DraftBX."
    icon: "fa fa-pencil-square" 

  - title: "Google-DRV"
    url: https://drive.google.com/drive/folders/0B5EzAQSIAOQgeFp6OWlRZVluOUk
    intro: "Google-DRV."
    icon: "fa fa-hdd-o"
  - title: "Taskworld-as-trello"
    url: https://enterprise.taskworld.com/s-chan/#/projects
    intro: "Taskworld-as-trello."
    icon: "fa fa-trello"
  - title: "Mind42-MindMap"
    url: https://mind42.com/
    intro: "Mind42-MindMap."
    icon: "fa fa-sitemap"

  - title: "Editing-Dynalist"
    url: https://dynalist.io/
    intro: "Editing-Dynalist."
    icon: "fa fa-pencil-square-o"
  - title: "Editing-GitBook"
    url: https://www.gitbook.com/@chan48/dashboard
    intro: "Editing-GitBook."
    icon: "fa fa-file-text" 
  - title: "G-Translator Toolkit"
    url: https://translate.google.com/toolkit/list?hl=ko#translations/active
    intro: "G-Translator Toolkit."
    icon: "fa fa-file-text" 

  - title: "Markdown-Mastering"
    url: https://guides.github.com/features/mastering-markdown/#examples
    intro: "My Linkin account."
    icon: "fa fa-file-text" 
  - title: "QuickMockup"
    url: https://jdittrich.github.io/quickMockup/
    intro: "QuickMockup."
    icon: "fa fa-picture-o" 
  - title: "Awesome-Icon"
    url: http://fontawesome.io/icons/
    intro: "Awesome icon."
    icon: "fa fa-file-image-o"
  - title: "Awesome-Vim"
    url: https://vimawesome.com/
    intro: "Awesome-Vim."
    icon: "fa fa-plug"

  - title: "Blog:Awesome-Dev"
    url: https://github.com/sarojaba/awesome-devblog
    intro: "Blog:Awesome-Dev."
    icon: "fa fa-star"
  - title: "Blog:DevO:AWSps"
    url: https://brunch.co.kr/magazine/devops
    intro: "Blog:AWS-DevOps."
    icon: "fa fa-pencil"
  - title: "Blog:애자일이야기"
    url: http://agile.egloos.com/5749946
    intro: "Blog:애자일이야기."
    icon: "fa fa-pencil"

  - title: "Pivotal-Agile"
    url: https://pivotal.io/kr/agile
    intro: "Pivotal-Agile."
    icon: "fa fa-th"
  - title: "Jira-Atlassian"
    url: https://quiz-aws.atlassian.net/secure/Dashboard.jspa
    intro: "Jira-Atlassian."
    icon: "fa fa-th"
  - title: "12 Factor-APP"
    url: https://12factor.net/ko/
    intro: "12factor-APP."
    icon: "fa fa-th"
  - title: "Salary-Calculate"
    url: https://stackoverflow.com/jobs/salary
    intro: "Salary-Calculate."
    icon: "fa fa-th"
  
  - title: "FreecodeCamp"
    url: https://www.freecodecamp.org/chan48
    intro: "FreecodeCamp."
    icon: "fa fa-list-alt"
  - title: "Hacker-Noon"
    url: https://hackernoon.com/javascript/home
    intro: "Hacker-Noon."
    icon: "fa fa-list-alt"
  - title: "AcloudGuru"
    url: https://acloud.guru/courses
    intro: "AcloudGuru."
    icon: "fa fa-list-alt"

  - title: "Udemy"
    url: https://www.udemy.com/home/my-courses/learning/
    intro: "Udemy."
    icon: "fa fa-list-alt"
  - title: "Inflearn"
    url: https://www.inflearn.com/members/chan-3/course/
    intro: "Inflearn."
    icon: "fa fa-list-alt"
  - title: "AskDjango-PY"
    url: https://nomade.kr/accounts/
    intro: "AskDjango."
    icon: "fa fa-list-alt"
  - title: "Nomadcoders-PY"
    url: http://academy.nomadcoders.co/courses/enrolled
    intro: "Nomadcoders."
    icon: "fa fa-list-alt"
  - title: "Marco-imagineer-PY"
    url: http://www.imagineer.io/p/python
    intro: "Marco-imagineer-PY."
    icon: "fa fa-list-alt"
  - title: "Codecademy"
    url: https://www.codecademy.com/learn
    intro: "Codecademy."
    icon: "fa fa-list-alt"
  - title: "RecursionJS"
    url: https://www.codecademy.com/courses/javascript-lesson-205/0/1
    intro: "RecursionJS."
    icon: "fa fa-list-alt"
  - title: "Udacity"
    url: https://classroom.udacity.com/me
    intro: "Udacity."
    icon: "fa fa-list-alt"  
  - title: "Coursera"
    url: https://www.coursera.org/
    intro: "Coursera."
    icon: "fa fa-list-alt"
  - title: "EDX"
    url: https://www.edx.org/
    intro: "EDX."
    icon: "fa fa-list-alt"
  - title: "생활코딩"
    url: https://opentutorials.org/course/2136
    intro: "생활코딩."
    icon: "fa fa-list-alt"
  - title: "칸아카데미"
    url: https://ko.khanacademy.org/computing
    intro: "칸아카데미."
    icon: "fa fa-list-alt"

  # AWS plus
  - title: "AWS-IAM"
    url:  https://com-chan.signin.aws.amazon.com/console
    intro: "Amazon-AWS-IAM."
    icon: "fa fa-users"
  - title: "AWS-Support-Plans"
    url: https://aws.amazon.com/ko/premiumsupport/compare-plans/
    intro: "AWS-Support Plans."
    icon: "fa fa-credit-card"
  - title: "AWS-Whitepapers"
    url: https://aws.amazon.com/ko/whitepapers/
    intro: "AWS-Whitepapers."
    icon: "fa fa-cloud"
  - title: "AWS-Webinar"
    url: https://aws.amazon.com/ko/blogs/korea/category/webinar/
    intro: "AWS-Webinar."
    icon: "fa fa-cloud"
  - title: "AWSKR-SlideShare"
    url: https://www.slideshare.net/awskorea/presentations
    intro: "AWSKR-SlideShare."
    icon: "fa fa-cloud"

  - title: "AWS-HandsOn-Qwiklabs"
    url: https://qwiklabs.com/catalog
    intro: "AWS-Study."
    icon: "fa fa-cloud"
  - title: "PIVOTAL-Cloud Foundry"
    url: https://console.run.pivotal.io/organizations/3ff75be5-8de8-4521-a2e6-0dccb6cbe1eb
    intro: "PIVOTAL-Cloud Foundry."
    icon: "fa fa-cloud"

  - title: "AWS IAM Reference"
    url: https://iam.cloudonaut.io/
    intro: "AWS IAM Reference."
    icon: "fa fa-book"
  - title: "AWS Quick Starts"
    url: https://aws.amazon.com/ko/quickstart/architecture/
    intro: "AWS Quick Starts."
    icon: "fa fa-book"
  
  - title: "DOCs:AWS-CLI"
    url: http://docs.aws.amazon.com/ko_kr/cli/latest/userguide/getting-help.html
    intro: "DOCs-AWS-CLI."
    icon: "fa fa-book"
  - title: "DOCs:AWS-CODECOMMIT"
    url: http://docs.aws.amazon.com/ko_kr/codecommit/latest/userguide/setting-up.html
    intro: "DOCs:AWS-CODECOMMIT."
    icon: "fa fa-book"
  - title: "DOCs:AWS-CODEPIPELINE"
    url: http://docs.aws.amazon.com/ko_kr/codepipeline/latest/userguide/welcome.html
    intro: "DOCs:AWS-CODEPIPELINE."
    icon: "fa fa-book"
  - title: "DOCs:AWS-Route53"
    url: http://docs.aws.amazon.com/ko_kr/Route53/latest/APIReference/Welcome.html
    intro: "DOCs:AWS-Route53."
    icon: "fa fa-book"

  - title: "DOCs:AWS-VPC"
    url: http://docs.aws.amazon.com/ko_kr/AmazonVPC/latest/UserGuide/VPC_Introduction.html
    intro: "DOCs:AWS-VPC."
    icon: "fa fa-book"
  - title: "DOCs:AWS-CloudFormation"
    url: http://docs.aws.amazon.com/ko_kr/AWSCloudFormation/latest/UserGuide/working-with-templates-cfn-designer-overview.html
    intro: "DOCs:AWS-CloudFormation."
    icon: "fa fa-book"
  - title: "DOCs:AWS-CloudWatch"
    url: http://docs.aws.amazon.com/ko_kr/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html
    intro: "DOCs:AWS-CloudWatch."
    icon: "fa fa-book"

  - title: "DOCs:AWS-ELB"
    url: http://docs.aws.amazon.com/ko_kr/elasticloadbalancing/latest/userguide/how-elastic-load-balancing-works.html
    intro: "DOCs:AWS-ELB."
    icon: "fa fa-book"
  - title: "DOCs:AWS-EC2"
    url: http://docs.aws.amazon.com/ko_kr/AWSEC2/latest/UserGuide/concepts.html
    intro: "DOCs:AWS-EC2."
    icon: "fa fa-book"
  - title: "DOCs:AWS-Dynamodb"
    url: http://docs.aws.amazon.com/ko_kr/amazondynamodb/latest/developerguide/Introduction.html
    intro: "DOCs:AWS-Dynamodb."
    icon: "fa fa-book"

  - title: "DOCs:AWS-APIGATEWAY"
    url: http://docs.aws.amazon.com/ko_kr/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html#api-gateway-simple-proxy-for-lambda-input-format
    intro: "APIG:AWSATEWAY."
    icon: "fa fa-book"
  - title: "DOCs:AWS-LAMBDA"
    url: http://docs.aws.amazon.com/ko_kr/lambda/latest/dg/welcome.html
    intro: "DOCs:AWS-LAMBDA."
    icon: "fa fa-book"
  - title: "DOCs:Serverless"
    url: https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
    intro: "DOCs:Serverless."
    icon: "fa fa-book"
  - title: "DOCs:RESTpatterns"
    url: https://restpatterns.mindtouch.us/HTTP_Status_Codes
    intro: "DOCs:Restpatterns."
    icon: "fa fa-book"
  
  - title: "DOCs:VulcanjsOnMeteror"
    url: http://docs.vulcanjs.org/example-movies.html
    intro: "DOCs:Vulcanjs."
    icon: "fa fa-book"
  - title: "DOCs:Meteor"
    url: https://guide.meteor.com/
    intro: "DOCs:MeteorPlatform."
    icon: "fa fa-book"
  - title: "DOCs:Graphql"
    url: http://graphql.org/learn/
    intro: "DOCs:Graphql."
    icon: "fa fa-book" 
  - title: "DOCs:Apollo"
    url: http://dev.apollodata.com/core/meteor.html#Examples
    intro: "DOCs:Apollo."
    icon: "fa fa-book" 

  - title: "Meteor Packages"
    url: https://atmospherejs.com/
    intro: "Meteor Packages."
    icon: "fa fa-book"
  - title: "Vulcanjs-Blog-Ref"
    url: http://spectrumdig.blogspot.kr/search?q=vulcan
    intro: "Vulcanjs-Blog-Ref."
    icon: "fa fa-book"
  - title: "Meteor-KR-Ref"
    url: http://kr.discovermeteor.com/
    intro: "Meteor-KR-Ref."
    icon: "fa fa-book"

  # DOCs plus
  - title: "Dev-DOC"
    url: http://devdocs.io/
    intro: "Dev-Doc."
    icon: "fa fa-book"   
  - title: "Node-DOC"
    url: https://nodejs.org/api/synopsis.html
    intro: "Node-DOC."
    icon: "fa fa-book"
  - title: "Node-Expressjs-DOC"
    url: http://expressjs.com/ko/4x/api.html
    intro: "Node>Expressjs-DOC."
    icon: "fa fa-book"
  - title: "React-DOC"
    url: https://facebook.github.io/react/docs/components-and-props.html
    intro: "React-DOC."
    icon: "fa fa-book"
  - title: "MERM-stack-DOC"
    url: http://mern.io/documentation.html
    intro: "MERM-stack-DOC."
    icon: "fa fa-book"

  - title: "MDN-JS-DOC"
    url: https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/
    intro: "MDN-JS-Doc."
    icon: "fa fa-book"
  - title: "Javascript-Info"
    url: https://javascript.info/
    intro: "Javascript-Info."
    icon: "fa fa-book"
  - title: "Web-Boss-JS-ES6"
    url: https://es6.io/
    intro: "Web-Boss-JS-ES6."
    icon: "fa fa-book"
  - title: "ECMAScript-Blg-Ref"
    url: https://perfectacle.github.io/categories/Programming/ECMAScript/
    intro: "ECMAScript-Blg-Ref."
    icon: "fa fa-book"

  - title: "Lib-lodash(UnderScore)"
    url: https://lodash.com/docs/4.17.4
    intro: "Lib-lodash(UnderScore)."
    icon: "fa fa-book"
  - title: "Lib-ramda"
    url: http://ramdajs.com/docs/
    intro: "Lib-ramda."
    icon: "fa fa-book"
  
  - title: "Coffee-DOC"
    url: http://coffeescript.org/#functions
    intro: "Coffeescript-DOC."
    icon: "fa fa-book"
  - title: "Python-DOC"
    url: https://docs.python.org/3.5/library/functions.html
    intro: "Python-Doc."
    icon: "fa fa-book"
  - title: "StackOver-Doc"
    url: https://stackoverflow.com/documentation/
    intro: "StackOverFlow-Doc."
    icon: "fa fa-stack-overflow"

  - title: "CODE-PEN"
    url: https://codepen.io/ch9/
    intro: "My CODE-PEN."
    icon: "fa fa-codepen"
  - title: "Plotly-DataVisualizePy"
    url: https://plot.ly/python/ipython-notebook-tutorial/#3d-plotting
    intro: "Plotly-DataVisualize."
    icon: "fa fa-eye"
  - title: "CDN-service:Unpkg"
    url: https://unpkg.com/#/stats
    intro: "CDN-service:Unpkg."
    icon: "fa fa-eye"
  - title: "CDN-service:Jsdelivr"
    url: https://www.jsdelivr.com/
    intro: "CDN-service:Jsdelivr."
    icon: "fa fa-eye"
  
  # IDE+
  - title: "Jupyterhub"
    url: https://play.dobest.io/hub/login
    intro: "Jupyterhub."
    icon: "fa fa-terminal"
  - title: "Yaml-parser"
    url: http://yaml-online-parser.appspot.com/
    intro: "Yaml-parser."
    icon: "fa fa-terminal"
  - title: "SWAPI-GraphQLer"
    url: http://graphql.org/swapi-graphql/
    intro: "SWAPI-GraphQLer."
    icon: "fa fa-terminal"
  - title: "Fiddles"
    url: https://fiddles.io/#
    intro: "Fiddles."
    icon: "fa fa-terminal"

  - title: "Cloud9-IDE"
    url: https://c9.io/chan48
    intro: "Cloud9-IDE."
    icon: "fa fa-terminal"
  - title: "ReactOnline-Editor"
    url: https://stackblitz.com/edit/react-sb6bgp
    intro: "ReactOnline-Editor."
    icon: "fa fa-terminal"
  - title: "Reactarmory-Ref"
    url: https://reactarmory.com/examples/hello-world/raw-hello-world
    intro: "Reactarmory-Ref."
    icon: "fa fa-terminal"

  - title: "Programmers-Algo"
    url: https://programmers.co.kr/learn/challenges
    intro: "Programmers-Algo."
    icon: "fa fa-code"
  - title: "CodeWars"
    url: https://www.codewars.com/users/chan48
    intro: "CodeWars."
    icon: "fa fa-code"
  - title: "Hacker-rank"
    url: https://www.hackerrank.com/dashboard
    intro: "Hacker-rank."
    icon: "fa fa-code"

  - title: "CodingInterView-1"
    url: https://www.youtube.com/playlist?list=PLVNY1HnUlO25sSWDr7CzVvkOF3bUgkiQQ
    intro: "CodingInterView-1."
    icon: "fa fa-youtube-play"
  - title: "CodingInterView-2"
    url: https://www.youtube.com/playlist?list=PLVNY1HnUlO24RlncfRjfoZHnD0YWVsvhq&v=piDwgBqmqKM
    intro: "CodingInterView-2."
    icon: "fa fa-youtube-play"

  - title: "YouTuberDev-codespitz"
    url: https://www.youtube.com/user/as3as3as3as3/feed
    intro: "YouTuberDev-codespitz."
    icon: "fa fa-youtube-play"
  - title: "YouTuberDev-velopert"
    url: https://www.youtube.com/channel/UCmMgRlN-3GKQ_CH7cOtLdvg/featured
    intro: "YouTuberDev-velopert."
    icon: "fa fa-youtube-play"
  - title: "YouTuberDev-Vulcan-Tutorial"
    url: https://www.youtube.com/channel/UCGIvQQ6zw7ov2cHgD70HFlA/playlists
    intro: "YouTuberDev-Vulcan-Tutorial."
    icon: "fa fa-youtube-play"
  - title: "YouTuberDev-Meteor-Tutorial"
    url: https://www.youtube.com/watch?v=BI8IslJHSag&list=PLLnpHn493BHFYZUSK62aVycgcAouqBt7V
    intro: "YouTuberDev-Meteor-Tutorial."
    icon: "fa fa-youtube-play"
  - title: "FramerjsByCoffee-Tutorial"
    url: https://www.udemy.com/framerjs-prototyping-design-interaction-animation/learn/v4/content
    intro: "FramerjsByCoffee-Tutorial."
    icon: "fa fa-youtube-play"
  - title: "Graphql-Tutorial"
    url: https://www.udemy.com/graphql-with-react-course/learn/v4/content
    intro: "FramerjsByCoffee-Tutorial."
    icon: "fa fa-youtube-play"

  # Personal
  - title: "S-CHAN Facebook"
    url: https://www.facebook.com/schan.choi.48
    intro: "My Facebook account."
    icon: "fa fa-facebook-square"
  - title: "S-CHAN Github"
    url: https://github.com/chan48
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "S-CHAN LinkedIn"
    url: https://www.linkedin.com/in/choi-seung-chan/
    intro: "My Linkin account."
    icon: "fa fa-linkedin-square"
    


widgets:
- search
- recent_comments
- category
- tagcloud
- recent_posts
- links

rss:
fancybox: true
favicon: favicon.png
duoshuo_shortname: #freemindtheme

# Analytics
google_analytics: 
  enable: true
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: true
jiathis: false


# built-in comment system
comment_js:
  type: "github"
  user: "chan48"
  repo: "chan48.github.io"
  client_id: "7179d6ca581e24cefa48"
  client_secret: "c48a9967591f833abb9b901f752e88875d8830f9"
  count: 5
