slogan: "POSTs"

theme: sandstone
inverse: false

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: "EditingMD-ByAdmin"
    url: http://prose.io/#chan48/chan48.github.io/tree/gh-pages/source
    intro: "My Github editor."
    icon: "fa fa-pencil-square"
  - title: "Editing-Dynalist"
    url: https://dynalist.io/
    intro: "Editing-Dynalist."
    icon: "fa fa-pencil-square-o"
  - title: "CODE-PEN"
    url: https://codepen.io/ch9/
    intro: "My CODE-PEN."
    icon: "fa fa-codepen"
  - title: "Markdown-Mastering"
    url: https://guides.github.com/features/mastering-markdown/#examples
    intro: "My Linkin account."
    icon: "fa fa-file-text"
  - title: "Awesome-Icon"
    url: http://fontawesome.io/icons/
    intro: "Awesome icon."
    icon: "fa fa-file-image-o"
  - title: "QuickMockup"
    url: https://jdittrich.github.io/quickMockup/
    intro: "QuickMockup."
    icon: "fa fa-picture-o"
  - title: "Taskworld-as-trello"
    url: https://enterprise.taskworld.com/s-chan/#/projects
    intro: "Taskworld-as-trello."
    icon: "fa fa-trello"
  - title: "Mind42-MindMap"
    url: https://mind42.com/
    intro: "Mind42-MindMap."
    icon: "fa fa-map-marker"
  - title: "Awesome-devblog"
    url: https://github.com/sarojaba/awesome-devblog
    intro: "Awesome-devblog."
    icon: "fa fa-star"
  - title: "AWS-HandsOn"
    url: https://qwiklabs.com/catalog
    intro: "AWS-Study."
    icon: "fa fa-cloud"

  - title: "CodeWars"
    url: https://www.codewars.com/users/chan48
    intro: "CodeWars."
    icon: "fa fa-code"
  - title: "Cloud9-IDE"
    url: https://c9.io/chan48
    intro: "Cloud9-IDE."
    icon: "fa fa-terminal"
  - title: "Goorm-IDE-TEST"
    url: https://codingtest.goorm.io/
    intro: "Goorm-TEST."
    icon: "fa fa-terminal"
  - title: "Hacker-rank"
    url: https://www.hackerrank.com/dashboard
    intro: "Hacker-rank."
    icon: "fa fa-hacker-news"
  - title: "FreecodeCamp"
    url: https://www.freecodecamp.org/chan48
    intro: "FreecodeCamp."
    icon: "fa fa-list-alt"
  - title: "StackOver-Doc"
    url: https://stackoverflow.com/documentation/
    intro: "StackOverFlow-Doc."
    icon: "fa fa-stack-overflow"
  - title: "Jira-Atlassian"
    url: https://quiz-aws.atlassian.net/secure/Dashboard.jspa
    intro: "Jira-Atlassian."
    icon: "fa fa-th"
  - title: "Amazon-AWS-IAM"
    url: https://console.aws.amazon.com/iam/
    intro: "Amazon-AWS-IAM."
    icon: "fa fa-amazon"
  - title: "Amazon-AWS-CODEPIPELINE"
    url: http://docs.aws.amazon.com/ko_kr/codepipeline/latest/userguide/welcome.html
    intro: "Amazon-AWS-CODEPIPELINE."
    icon: "fa fa-amazon"
  - title: "Amazon-AWS-DOCs"
    url: http://docs.aws.amazon.com/ko_kr/codecommit/latest/userguide/welcome.html
    intro: "Amazon-AWS-DOCs."
    icon: "fa fa-amazon"
  - title: "Amazon-AWS-DevOpsBlog"
    url: https://brunch.co.kr/magazine/devops
    intro: "Amazon-AWS-DevOpsBlog."
    icon: "fa fa-amazon"

  - title: "S-CHAN Facebook"
    url: https://www.facebook.com/schan.choi.48
    intro: "My Facebook account."
    icon: "fa fa-facebook-square"
  - title: "S-CHAN Github"
    url: https://github.com/chan48
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "S-CHAN LinkedIn"
    url: https://www.linkedin.com/in/choi-seung-chan/
    intro: "My Linkin account."
    icon: "fa fa-linkedin-square"
 
 

    


widgets:
- search
- recent_comments
- category
- tagcloud
- recent_posts
- links

rss:
fancybox: true
favicon: favicon.png
duoshuo_shortname: #freemindtheme

# Analytics
google_analytics: 
  enable: true
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: true
jiathis: false


# built-in comment system
comment_js:
  type: "github"
  user: "chan48"
  repo: "chan48.github.io"
  client_id: "7179d6ca581e24cefa48"
  client_secret: "c48a9967591f833abb9b901f752e88875d8830f9"
  count: 5
